spring.application.name=graphQLearningSpring

# H2 Database Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:blogdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'create-drop' creates a fresh schema on each restart
spring.jpa.hibernate.ddl-auto=update

# Modern Spring GraphQL Configuration
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Prevents queries deeper than 5 fields, throwing an automatic validation error
spring.graphql.parser.max-tokens=15000
spring.graphql.schema.inspection.enabled=true

spring.graphql.query-by-example.enabled=false
rsa.private-key=classpath:certs/app-private.pem
rsa.public-key=classpath:certs/app-public.pem